name: Deploy Lambda

on:
  push:
    paths:
      - 'lambda/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip Lambda
        run: |
          cd lambda
          zip -r lambda.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/aws-lambda-deploy@v1.0.0
        with:
          function_name: event-ingestion
          zip_file: lambda/lambda.zip
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
