name: Lambda Deploy (FINAL)

on:
  workflow_dispatch:   # manual run (no auto confusion)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: Zip Lambda
        run: |
          cd lambda
          zip -r lambda.zip .

      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name event-ingestion \
            --zip-file fileb://lambda/lambda.zip
